# Generated by Django 6.0.3 on 2026-03-14 08:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('reach', models.IntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0)),
                ('raw_data', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'post_analytics',
                'ordering': ['-snapshot_at'],
            },
        ),
        migrations.CreateModel(
            name='PublishLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField()),
                ('response_data', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('attempt_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'publish_logs',
                'ordering': ['-attempt_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custom_caption', models.TextField(blank=True)),
                ('custom_hashtags', models.JSONField(default=list)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('platform_post_id', models.CharField(blank=True, max_length=255)),
                ('platform_url', models.URLField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('shares_count', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('reach', models.IntegerField(default=0)),
                ('analytics_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scheduled_posts',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
