# Generated by Django 6.0.3 on 2026-03-14 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0001_initial'),
        ('users', '0001_initial'),
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to='videos.videoproject'),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='social_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to='users.socialaccount'),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publishlog',
            name='scheduled_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_logs', to='social.scheduledpost'),
        ),
        migrations.AddField(
            model_name='postanalytics',
            name='scheduled_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='social.scheduledpost'),
        ),
    ]
