# Generated by Django 4.2.9 on 2026-04-06 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('share', 'Share')], max_length=20)),
                ('platform', models.CharField(blank=True, max_length=30)),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('actor_id', models.CharField(blank=True, max_length=255)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('target_url', models.URLField(blank=True)),
                ('analytics_target', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='social.scheduledpost')),
            ],
            options={
                'db_table': 'post_activity_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
