# Generated by Django 4.2.9 on 2026-05-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_scheduledpost_platform_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('blocked', 'Blocked')], default='scheduled', max_length=20),
        ),
    ]
