# Generated by Django 4.2.9 on 2026-05-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_free_plan_video_quota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeyconfig',
            name='service',
            field=models.CharField(choices=[('openai', 'OpenAI / ChatGPT'), ('deepseek', 'DeepSeek'), ('groq', 'Groq (xAI)'), ('elevenlabs', 'ElevenLabs (TTS)'), ('pexels', 'Pexels (Video Footage)'), ('stability', 'Stability AI'), ('runway', 'Runway ML'), ('anthropic', 'Anthropic (Claude)'), ('mistral', 'Mistral AI'), ('cohere', 'Cohere'), ('others', 'Others (Custom API)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube Shorts'), ('twitter', 'Twitter/X')], max_length=30),
        ),
        migrations.AlterField(
            model_name='verificationotp',
            name='purpose',
            field=models.CharField(choices=[('register', 'Register'), ('login', 'Login'), ('profile_contact', 'Profile Contact'), ('password_reset', 'Password Reset')], max_length=20),
        ),
    ]
