# Generated by Django 4.2.9 on 2026-05-26 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_apikeyconfig_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('action', models.CharField(choices=[('register', 'Register'), ('login', 'Login'), ('logout', 'Logout'), ('password_reset', 'Password Reset'), ('email_verified', 'Email Verified'), ('profile_updated', 'Profile Updated'), ('email_changed', 'Email Changed'), ('subscription_activated', 'Subscription Activated'), ('subscription_cancelled', 'Subscription Cancelled'), ('subscription_suspended', 'Subscription Suspended'), ('subscription_expired', 'Subscription Expired'), ('subscription_refunded', 'Subscription Refunded'), ('payment_completed', 'Payment Completed'), ('payment_failed', 'Payment Failed'), ('video_quota_consumed', 'Video Quota Consumed'), ('account_deleted', 'Account Deleted')], max_length=40)),
                ('detail', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
