# Generated by Django 4.2.9 on 2026-06-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_subscription_usage_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
