# Generated by Django 6.0.3 on 2026-03-14 08:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('promotional', 'Promotional'), ('educational', 'Educational'), ('entertainment', 'Entertainment'), ('announcement', 'Announcement'), ('testimonial', 'Testimonial'), ('tutorial', 'Tutorial'), ('story', 'Story')], default='promotional', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('review', 'Ready for Review'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('topic', models.TextField(help_text='What the video should be about')),
                ('target_audience', models.CharField(blank=True, max_length=255)),
                ('tone', models.CharField(blank=True, help_text='professional, casual, energetic, calm, etc.', max_length=50)),
                ('duration_seconds', models.IntegerField(default=30)),
                ('ai_service', models.CharField(default='openai', help_text='Which AI service to use for generation', max_length=30)),
                ('ai_script', models.TextField(blank=True)),
                ('ai_caption', models.TextField(blank=True)),
                ('ai_hashtags', models.JSONField(default=list)),
                ('ai_keywords', models.JSONField(default=list)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/generated/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('video_url', models.URLField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('duration_actual', models.FloatField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=20)),
                ('format', models.CharField(blank=True, default='mp4', max_length=10)),
                ('edited_caption', models.TextField(blank=True)),
                ('edited_hashtags', models.JSONField(default=list)),
                ('user_notes', models.TextField(blank=True)),
                ('generation_task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'video_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('background', 'Background Video/Image'), ('logo', 'Logo/Watermark'), ('music', 'Background Music'), ('voiceover', 'Voiceover Audio'), ('font', 'Custom Font'), ('overlay', 'Overlay Image')], max_length=30)),
                ('file', models.FileField(upload_to='assets/')),
                ('file_url', models.URLField(blank=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='videos.videoproject')),
            ],
            options={
                'db_table': 'video_assets',
            },
        ),
        migrations.CreateModel(
            name='GenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_service', models.CharField(max_length=30)),
                ('prompt_used', models.TextField()),
                ('response_data', models.JSONField(default=dict)),
                ('tokens_used', models.IntegerField(null=True)),
                ('cost_estimate', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('duration_seconds', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_logs', to='videos.videoproject')),
            ],
            options={
                'db_table': 'generation_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(max_length=30)),
                ('template_data', models.JSONField(default=dict, help_text='Template config: colors, fonts, transitions, etc.')),
                ('preview_url', models.URLField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'video_templates',
            },
        ),
    ]
