# Generated by Django 4.2.9 on 2026-05-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_videoproject_platform_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoproject',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('review', 'Ready for Review'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed'), ('blocked', 'Blocked')], default='draft', max_length=20),
        ),
    ]
